project:
  type: website
  output-dir: docs

execute: 
  freeze: true

website:
  title: ""
  description: "Carter M. Smith's Personal Website"
  open-graph: true
  page-footer: 
    center: 
      Â© 2026 Carter M. Smith | Made with [Quarto](https://quarto.org)
  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        href: index.qmd
      - text: "Research"
        href: /research/
      - text: "Projects"
        href: /projects/
      - text: "Blog"
        href: /blog/
      - text: "CV"
        href: /cv/cv_jan2026.pdf
        target: _blank
    tools:
      - icon: "github"
        menu:
        - text: Source Code
          href: https://github.com/cartermsmith/website.git
        - text: Report a Bug
          href: .github/ISSUE_TEMPLATE/bug_report.md
    collapse: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



